// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPY_skQKTlNB0f_vljFbX8qLK6sSPB5TI',
    appId: '1:247798777710:web:9e99e9c77d4d75bb22a37f',
    messagingSenderId: '247798777710',
    projectId: 'clone-25685',
    authDomain: 'clone-25685.firebaseapp.com',
    storageBucket: 'clone-25685.firebasestorage.app',
    measurementId: 'G-1N85171W1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInvJbTRaMTydINnX_zrgg6QUDN27QcPw',
    appId: '1:247798777710:android:70e54d4f0059d69a22a37f',
    messagingSenderId: '247798777710',
    projectId: 'clone-25685',
    storageBucket: 'clone-25685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FgJJl7FJDYN726QG1ASt5EaRkVvYNnM',
    appId: '1:247798777710:ios:fc6497db29afb34e22a37f',
    messagingSenderId: '247798777710',
    projectId: 'clone-25685',
    storageBucket: 'clone-25685.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FgJJl7FJDYN726QG1ASt5EaRkVvYNnM',
    appId: '1:247798777710:ios:fc6497db29afb34e22a37f',
    messagingSenderId: '247798777710',
    projectId: 'clone-25685',
    storageBucket: 'clone-25685.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPY_skQKTlNB0f_vljFbX8qLK6sSPB5TI',
    appId: '1:247798777710:web:6d4fdf0d128a44a422a37f',
    messagingSenderId: '247798777710',
    projectId: 'clone-25685',
    authDomain: 'clone-25685.firebaseapp.com',
    storageBucket: 'clone-25685.firebasestorage.app',
    measurementId: 'G-JBE7J250M1',
  );
}
